name: bswl_frontend_app
description: Sign Language Learning App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## ── Firebase core & Auth ─────────────────────────────────────────────────
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

  ## ── Google Sign-In ───────────────────────────────────────────────────────
  google_sign_in: ^6.3.0

  ## ── Internationalization / Date formatting ──────────────────────────────
  intl: ^0.20.2

  ## ── UI & Icons ───────────────────────────────────────────────────────────
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.2

  ## ── State Management ────────────────────────────────────────────────────
  provider: ^6.0.5

  ## ── Camera & ML ─────────────────────────────────────────────────────────
  camera: ^0.11.1
  google_ml_kit: ^0.20.0

  ## ── Networking ──────────────────────────────────────────────────────────
  http: ^1.2.1

  ## ── Animations & Effects ─────────────────────────────────────────────────
  lottie: ^3.3.1
  shimmer: ^3.0.0
  flutter_animate: ^4.1.1

  ## ── Caching & Vibration ─────────────────────────────────────────────────
  cached_network_image: ^3.3.0
  vibration: ^3.1.3

  ## ── Icons ─────────────────────────────────────────────────────────────────
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/
    - assets/animations/namaste.json
    - assets/animations/thankyou.json
    - assets/animations/hello.json
    - assets/animations/BOY1.json
    - assets/animations/BOY2.json
    - assets/animations/GIRL.json
    - assets/animations/student.json


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500